### ISSUE TITLE
500 issue

### ISSUE THREAD

**Issue by DenisChulkov** [gurock/testrail-api#11]
Hi guys,

Every time when I try get or set any attribute in test or testcase I see 500 error. It looks like you forgot to add httpWebRequest.UserAgent = ".NET Framework Test Client"; to the SendRequest method. With this string of code all works fine. Could you please recheck and update codebase?
![image](https://user-images.githubusercontent.com/6906182/38499744-38716488-3c11-11e8-8f50-77b06b014abf.png)

**Comment by jonrgurock** [comment]
Hi @DenisChulkov,

I am closing this issue due to its age and lack of additional error reports. If this is still an issue, please reach out to our support team at contact@gurock.com so we can troubleshoot this further.

Regards,
Jon
