### ISSUE TITLE
Feature request - Add sortable indexes on user defined entites (test runs, cases, plans, test inside of a test run)

### ISSUE THREAD

**Issue by bbeale** [gurock/testrail-api#24]
In the `section` object, there is a `display_order` field that I expect to be able to modify with update_section. It would be very useful to have a similar functionality with all user defined entities.

**Comment by jonrgurock** [comment]
Hi @bbeale, Thanks for the request! I have added your feature request to our internal system so we can consider this for a future TestRail update.

Regards,
Jon
