### ISSUE TITLE
is there a testrail-api nuget package available?

### ISSUE THREAD

**Issue by alexlazarciuc** [gurock/testrail-api#28]
I am just wondering if there is a nuget testrail-api package available?

**Comment by jonrgurock** [comment]
Hi @alexlazarciuc,

We do not have an official NuGet package available for TestRail's API. However, there are third-party packages available for various languages which appear to be regularly maintained. Here is one example:

https://www.nuget.org/packages/TestRail/

Please keep in mind that this package is not maintained by our team, so we might not be able to support some issues which arise when using this package.

Regards,
Jon
