### ISSUE TITLE
Functional: No way to add the test case to a test run while creating the test case

### ISSUE THREAD

**Issue by mahvishsiddiqui** [gurock/testrail-api#4]
Pre requisite: Existing Test run with some test cases selected from Test Suites section

Steps:
1. Go to Test Suites, add a new test case. Check if you can add this test case to active test runs

Actual Result: 
1. No option to add current test case to an active test run

Expected result:
1. Add a drop list feature 'Add to Test Run' (or Test Plan) in the navigation bar between  Add Case, and Edit.
2. Clicking on the drop list should display a list of active test runs only 
3. Should allow selecting multiple cases at once from test suite section and add to a test run without requiring to go to test run tab

**Comment by dgurock** [comment]
Hello,

Thanks for the request. Is this a request for the TestRail API or a general TestRail request? For general requests please make sure to contact our support, as this issue list would only apply to the TestRail API bindings:

http://www.gurock.com/testrail/support/

Regarding your request: if your test run was created with the Include All option, new test cases would automatically be included. If you have a custom case selection, you would edit the test run to add cases as needed.
